sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                sku_widget:
                    template: "@SyliusShop/Product/Show/_sku.html.twig"
                    priority: 29
